/// <reference types="react" />
import { StylesConfig } from 'react-select';
export declare const SelectStyled: import("@emotion/styled").StyledComponent<Omit<Pick<import("react-select/base").Props<unknown, boolean, import("react-select").GroupBase<unknown>>, "className" | "onFocus" | "onBlur" | "form" | "theme" | "id" | "aria-errormessage" | "aria-invalid" | "aria-label" | "aria-labelledby" | "onChange" | "onKeyDown" | "value" | "required" | "ariaLiveMessages" | "autoFocus" | "classNamePrefix" | "delimiter" | "formatOptionLabel" | "hideSelectedOptions" | "inputValue" | "inputId" | "instanceId" | "isClearable" | "isOptionSelected" | "menuPortalTarget" | "name" | "onInputChange" | "onMenuOpen" | "onMenuClose" | "onMenuScrollToTop" | "onMenuScrollToBottom"> & Partial<Pick<import("react-select/base").Props<unknown, boolean, import("react-select").GroupBase<unknown>>, "placeholder" | "tabIndex" | "aria-live" | "styles" | "components" | "backspaceRemovesValue" | "blurInputOnSelect" | "captureMenuScroll" | "classNames" | "closeMenuOnSelect" | "closeMenuOnScroll" | "controlShouldRenderValue" | "escapeClearsValue" | "filterOption" | "formatGroupLabel" | "getOptionLabel" | "getOptionValue" | "isDisabled" | "isLoading" | "isOptionDisabled" | "isMulti" | "isRtl" | "isSearchable" | "loadingMessage" | "minMenuHeight" | "maxMenuHeight" | "menuIsOpen" | "menuPlacement" | "menuPosition" | "menuShouldBlockScroll" | "menuShouldScrollIntoView" | "noOptionsMessage" | "openMenuOnFocus" | "openMenuOnClick" | "options" | "pageSize" | "screenReaderStatus" | "tabSelectsValue" | "unstyled">> & Partial<Pick<{
    'aria-live': string;
    backspaceRemovesValue: boolean;
    blurInputOnSelect: boolean;
    captureMenuScroll: boolean;
    classNames: {};
    closeMenuOnSelect: boolean;
    closeMenuOnScroll: boolean;
    components: {};
    controlShouldRenderValue: boolean;
    escapeClearsValue: boolean;
    filterOption: (option: import("react-select/dist/declarations/src/filters").FilterOptionOption<unknown>, rawInput: string) => boolean;
    formatGroupLabel: <Option_1, Group_1 extends import("react-select").GroupBase<Option_1>>(group: Group_1) => string;
    getOptionLabel: <Option_2>(option: Option_2) => string;
    getOptionValue: <Option_3>(option: Option_3) => string;
    isDisabled: boolean;
    isLoading: boolean;
    isMulti: boolean;
    isRtl: boolean;
    isSearchable: boolean;
    isOptionDisabled: <Option_4>(option: Option_4) => boolean;
    loadingMessage: () => string;
    maxMenuHeight: number;
    minMenuHeight: number;
    menuIsOpen: boolean;
    menuPlacement: string;
    menuPosition: string;
    menuShouldBlockScroll: boolean;
    menuShouldScrollIntoView: boolean;
    noOptionsMessage: () => string;
    openMenuOnFocus: boolean;
    openMenuOnClick: boolean;
    options: never[];
    pageSize: number;
    placeholder: string;
    screenReaderStatus: ({ count }: {
        count: number;
    }) => string;
    styles: {};
    tabIndex: number;
    tabSelectsValue: boolean;
    unstyled: boolean;
}, never>>, "onChange" | "value" | "inputValue" | "menuIsOpen" | "onInputChange" | "onMenuOpen" | "onMenuClose"> & Partial<Pick<import("react-select/base").Props<unknown, boolean, import("react-select").GroupBase<unknown>>, "className" | "onFocus" | "onBlur" | "form" | "theme" | "id" | "aria-errormessage" | "aria-invalid" | "aria-label" | "aria-labelledby" | "onChange" | "onKeyDown" | "value" | "required" | "ariaLiveMessages" | "autoFocus" | "classNamePrefix" | "delimiter" | "formatOptionLabel" | "hideSelectedOptions" | "inputValue" | "inputId" | "instanceId" | "isClearable" | "isOptionSelected" | "menuPortalTarget" | "name" | "onInputChange" | "onMenuOpen" | "onMenuClose" | "onMenuScrollToTop" | "onMenuScrollToBottom"> & Partial<Pick<import("react-select/base").Props<unknown, boolean, import("react-select").GroupBase<unknown>>, "placeholder" | "tabIndex" | "aria-live" | "styles" | "components" | "backspaceRemovesValue" | "blurInputOnSelect" | "captureMenuScroll" | "classNames" | "closeMenuOnSelect" | "closeMenuOnScroll" | "controlShouldRenderValue" | "escapeClearsValue" | "filterOption" | "formatGroupLabel" | "getOptionLabel" | "getOptionValue" | "isDisabled" | "isLoading" | "isOptionDisabled" | "isMulti" | "isRtl" | "isSearchable" | "loadingMessage" | "minMenuHeight" | "maxMenuHeight" | "menuIsOpen" | "menuPlacement" | "menuPosition" | "menuShouldBlockScroll" | "menuShouldScrollIntoView" | "noOptionsMessage" | "openMenuOnFocus" | "openMenuOnClick" | "options" | "pageSize" | "screenReaderStatus" | "tabSelectsValue" | "unstyled">> & Partial<Pick<{
    'aria-live': string;
    backspaceRemovesValue: boolean;
    blurInputOnSelect: boolean;
    captureMenuScroll: boolean;
    classNames: {};
    closeMenuOnSelect: boolean;
    closeMenuOnScroll: boolean;
    components: {};
    controlShouldRenderValue: boolean;
    escapeClearsValue: boolean;
    filterOption: (option: import("react-select/dist/declarations/src/filters").FilterOptionOption<unknown>, rawInput: string) => boolean;
    formatGroupLabel: <Option_1, Group_1 extends import("react-select").GroupBase<Option_1>>(group: Group_1) => string;
    getOptionLabel: <Option_2>(option: Option_2) => string;
    getOptionValue: <Option_3>(option: Option_3) => string;
    isDisabled: boolean;
    isLoading: boolean;
    isMulti: boolean;
    isRtl: boolean;
    isSearchable: boolean;
    isOptionDisabled: <Option_4>(option: Option_4) => boolean;
    loadingMessage: () => string;
    maxMenuHeight: number;
    minMenuHeight: number;
    menuIsOpen: boolean;
    menuPlacement: string;
    menuPosition: string;
    menuShouldBlockScroll: boolean;
    menuShouldScrollIntoView: boolean;
    noOptionsMessage: () => string;
    openMenuOnFocus: boolean;
    openMenuOnClick: boolean;
    options: never[];
    pageSize: number;
    placeholder: string;
    screenReaderStatus: ({ count }: {
        count: number;
    }) => string;
    styles: {};
    tabIndex: number;
    tabSelectsValue: boolean;
    unstyled: boolean;
}, never>>> & import("react-select/dist/declarations/src/useStateManager").StateManagerAdditionalProps<unknown> & import("react").RefAttributes<import("react-select/base").default<unknown, boolean, import("react-select").GroupBase<unknown>>> & {
    theme?: import("@emotion/react").Theme;
} & Omit<Pick<import("react-select/base").Props<import("./Select").SelectOption, boolean, import("react-select").GroupBase<import("./Select").SelectOption>>, "className" | "onFocus" | "onBlur" | "form" | "theme" | "id" | "aria-errormessage" | "aria-invalid" | "aria-label" | "aria-labelledby" | "onChange" | "onKeyDown" | "value" | "required" | "ariaLiveMessages" | "autoFocus" | "classNamePrefix" | "delimiter" | "formatOptionLabel" | "hideSelectedOptions" | "inputValue" | "inputId" | "instanceId" | "isClearable" | "isOptionSelected" | "menuPortalTarget" | "name" | "onInputChange" | "onMenuOpen" | "onMenuClose" | "onMenuScrollToTop" | "onMenuScrollToBottom"> & Partial<Pick<import("react-select/base").Props<import("./Select").SelectOption, boolean, import("react-select").GroupBase<import("./Select").SelectOption>>, "placeholder" | "tabIndex" | "aria-live" | "styles" | "components" | "backspaceRemovesValue" | "blurInputOnSelect" | "captureMenuScroll" | "classNames" | "closeMenuOnSelect" | "closeMenuOnScroll" | "controlShouldRenderValue" | "escapeClearsValue" | "filterOption" | "formatGroupLabel" | "getOptionLabel" | "getOptionValue" | "isDisabled" | "isLoading" | "isOptionDisabled" | "isMulti" | "isRtl" | "isSearchable" | "loadingMessage" | "minMenuHeight" | "maxMenuHeight" | "menuIsOpen" | "menuPlacement" | "menuPosition" | "menuShouldBlockScroll" | "menuShouldScrollIntoView" | "noOptionsMessage" | "openMenuOnFocus" | "openMenuOnClick" | "options" | "pageSize" | "screenReaderStatus" | "tabSelectsValue" | "unstyled">> & Partial<Pick<{
    'aria-live': string;
    backspaceRemovesValue: boolean;
    blurInputOnSelect: boolean;
    captureMenuScroll: boolean;
    classNames: {};
    closeMenuOnSelect: boolean;
    closeMenuOnScroll: boolean;
    components: {};
    controlShouldRenderValue: boolean;
    escapeClearsValue: boolean;
    filterOption: (option: import("react-select/dist/declarations/src/filters").FilterOptionOption<unknown>, rawInput: string) => boolean;
    formatGroupLabel: <Option_1, Group_1 extends import("react-select").GroupBase<Option_1>>(group: Group_1) => string;
    getOptionLabel: <Option_2>(option: Option_2) => string;
    getOptionValue: <Option_3>(option: Option_3) => string;
    isDisabled: boolean;
    isLoading: boolean;
    isMulti: boolean;
    isRtl: boolean;
    isSearchable: boolean;
    isOptionDisabled: <Option_4>(option: Option_4) => boolean;
    loadingMessage: () => string;
    maxMenuHeight: number;
    minMenuHeight: number;
    menuIsOpen: boolean;
    menuPlacement: string;
    menuPosition: string;
    menuShouldBlockScroll: boolean;
    menuShouldScrollIntoView: boolean;
    noOptionsMessage: () => string;
    openMenuOnFocus: boolean;
    openMenuOnClick: boolean;
    options: never[];
    pageSize: number;
    placeholder: string;
    screenReaderStatus: ({ count }: {
        count: number;
    }) => string;
    styles: {};
    tabIndex: number;
    tabSelectsValue: boolean;
    unstyled: boolean;
}, never>>, "onChange" | "value" | "inputValue" | "menuIsOpen" | "onInputChange" | "onMenuOpen" | "onMenuClose"> & Partial<Pick<import("react-select/base").Props<import("./Select").SelectOption, boolean, import("react-select").GroupBase<import("./Select").SelectOption>>, "className" | "onFocus" | "onBlur" | "form" | "theme" | "id" | "aria-errormessage" | "aria-invalid" | "aria-label" | "aria-labelledby" | "onChange" | "onKeyDown" | "value" | "required" | "ariaLiveMessages" | "autoFocus" | "classNamePrefix" | "delimiter" | "formatOptionLabel" | "hideSelectedOptions" | "inputValue" | "inputId" | "instanceId" | "isClearable" | "isOptionSelected" | "menuPortalTarget" | "name" | "onInputChange" | "onMenuOpen" | "onMenuClose" | "onMenuScrollToTop" | "onMenuScrollToBottom"> & Partial<Pick<import("react-select/base").Props<import("./Select").SelectOption, boolean, import("react-select").GroupBase<import("./Select").SelectOption>>, "placeholder" | "tabIndex" | "aria-live" | "styles" | "components" | "backspaceRemovesValue" | "blurInputOnSelect" | "captureMenuScroll" | "classNames" | "closeMenuOnSelect" | "closeMenuOnScroll" | "controlShouldRenderValue" | "escapeClearsValue" | "filterOption" | "formatGroupLabel" | "getOptionLabel" | "getOptionValue" | "isDisabled" | "isLoading" | "isOptionDisabled" | "isMulti" | "isRtl" | "isSearchable" | "loadingMessage" | "minMenuHeight" | "maxMenuHeight" | "menuIsOpen" | "menuPlacement" | "menuPosition" | "menuShouldBlockScroll" | "menuShouldScrollIntoView" | "noOptionsMessage" | "openMenuOnFocus" | "openMenuOnClick" | "options" | "pageSize" | "screenReaderStatus" | "tabSelectsValue" | "unstyled">> & Partial<Pick<{
    'aria-live': string;
    backspaceRemovesValue: boolean;
    blurInputOnSelect: boolean;
    captureMenuScroll: boolean;
    classNames: {};
    closeMenuOnSelect: boolean;
    closeMenuOnScroll: boolean;
    components: {};
    controlShouldRenderValue: boolean;
    escapeClearsValue: boolean;
    filterOption: (option: import("react-select/dist/declarations/src/filters").FilterOptionOption<unknown>, rawInput: string) => boolean;
    formatGroupLabel: <Option_1, Group_1 extends import("react-select").GroupBase<Option_1>>(group: Group_1) => string;
    getOptionLabel: <Option_2>(option: Option_2) => string;
    getOptionValue: <Option_3>(option: Option_3) => string;
    isDisabled: boolean;
    isLoading: boolean;
    isMulti: boolean;
    isRtl: boolean;
    isSearchable: boolean;
    isOptionDisabled: <Option_4>(option: Option_4) => boolean;
    loadingMessage: () => string;
    maxMenuHeight: number;
    minMenuHeight: number;
    menuIsOpen: boolean;
    menuPlacement: string;
    menuPosition: string;
    menuShouldBlockScroll: boolean;
    menuShouldScrollIntoView: boolean;
    noOptionsMessage: () => string;
    openMenuOnFocus: boolean;
    openMenuOnClick: boolean;
    options: never[];
    pageSize: number;
    placeholder: string;
    screenReaderStatus: ({ count }: {
        count: number;
    }) => string;
    styles: {};
    tabIndex: number;
    tabSelectsValue: boolean;
    unstyled: boolean;
}, never>>> & import("react-select/dist/declarations/src/useStateManager").StateManagerAdditionalProps<import("./Select").SelectOption>, {}, {}>;
export declare const customStyles: StylesConfig;
